# -*- coding: utf-8 -*-
"""22-04-25 PMN - Prueba2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10x90V3O6nKtSgBAS04PUUZLK4mR7fLSi
"""



"""Prueba"""



a=1

